spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  ai:
    vectorstore:
      redis:
        initialize: true
        dimensions: 1024
        index: rag-index



    openai:
      # 👇 替换为你的第三方平台API密钥
      api-key: xxxx
      # 👇 替换为第三方平台的base_url，必须带/v1
      base-url: xxxx/v1
      chat:
        # 👇 替换为第三方平台的模型名
        model: mimo-v2.5

  profiles:
    active: secret
server:
  port: 8080
